// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Category struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type Clothes struct {
	ID       int     `json:"id"`
	Name     string  `json:"name"`
	IDStore  int     `json:"id_store"`
	Category int     `json:"category"`
	Size     string  `json:"size"`
	Price    float64 `json:"price"`
	Quantity int     `json:"quantity"`
}

type Store struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	StoreID     int    `json:"storeId"`
	Cnpj        string `json:"cnpj"`
	PhoneNumber string `json:"phoneNumber"`
	Address     string `json:"address"`
	Category    int    `json:"category"`
}

type CreateCategoryInput struct {
	Name string `json:"name"`
}

type CreateClothInput struct {
	Name     string  `json:"name"`
	IDStore  int     `json:"id_store"`
	Category int     `json:"category"`
	Size     string  `json:"size"`
	Price    float64 `json:"price"`
	Quantity int     `json:"quantity"`
}

type CreateStoreInput struct {
	Name        string `json:"name"`
	Cnpj        string `json:"cnpj"`
	PhoneNumber string `json:"phoneNumber"`
	Address     string `json:"address"`
	Category    int    `json:"category"`
}

type UpdateCategoryInput struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type UpdateClothInput struct {
	ID       int     `json:"id"`
	Name     string  `json:"name"`
	IDStore  int     `json:"id_store"`
	Category int     `json:"category"`
	Size     string  `json:"size"`
	Price    float64 `json:"price"`
	Quantity int     `json:"quantity"`
}

type UpdateStoreInput struct {
	ID          int    `json:"id"`
	Name        string `json:"name"`
	Cnpj        string `json:"cnpj"`
	PhoneNumber string `json:"phoneNumber"`
	Address     string `json:"address"`
	Category    int    `json:"category"`
}
