name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: go test -gcflags=all=-l -race -coverprofile=profile.cov ./pkg/graphql/models ./pkg/entity ./pkg/graphql/resolvers ./services

      - name: Coverage
        run: go tool cover -func profile.cov